allow-lan: true
dns:
  enable: true
  nameserver:
  - 114.114.114.114
  - 8.8.8.8
external-controller: 0.0.0.0:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
- name: HK1
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpchongkong2/
- name: HK2
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcsg2/?ed=2560
- name: HK3
  network: ws
  port: 80
  server: qsynode-01.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsynode-01.1000ws.top
    path: /grpchongkong3/
- name: JP1
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcjapan1/?ed=2560
- name: JP2
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcjapan2/?ed=2560
- name: TW1
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpchongkong1/
- name: SG1
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcsg1/
- name: US1
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: ead3d77d-1fbd-41b7-9f8b-bcbc6af96f86
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcus1/
- alterId: 0
  cipher: auto
  name: 🇭🇰 香港_03
  network: ws
  port: 44552
  server: hk03.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: ee7c08a6-1682-4219-bbfc-14faca3843a1
  ws-opts:
    path: ''
- name: 🇭🇰+香港-07
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 44302
  server: hk07.jsytongxin.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- alterId: 0
  cipher: auto
  name: 🇭🇰 香港_09
  network: ws
  port: 51254
  server: hk18.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: ee7c08a6-1682-4219-bbfc-14faca3843a1
  ws-opts:
    path: ''
- name: 🇯🇵+日本-13
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 30502
  server: jp13.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: 🇯🇵+日本-14
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 39204
  server: jp14.jsyjiedian8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: 🇯🇵+日本-15
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 39555
  server: jp15.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: 🇸🇬+新加坡-13
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 45177
  server: sg13.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: 🇸🇬+新加坡-14
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 45078
  server: sg14.jsyjiedian8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: 🇸🇬+新加坡-15
  password: ee7c08a6-1682-4219-bbfc-14faca3843a1
  port: 45179
  server: sg15.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- alterId: 0
  cipher: auto
  name: 🇺🇸 美国-08
  network: ws
  port: 40601
  server: us05.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: ee7c08a6-1682-4219-bbfc-14faca3843a1
  ws-opts:
    path: ''
- alterId: 0
  cipher: auto
  name: 🇺🇸 美国-09
  network: ws
  port: 40706
  server: us09.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: ee7c08a6-1682-4219-bbfc-14faca3843a1
  ws-opts:
    path: ''
- alterId: 0
  cipher: auto
  name: 🇺🇸 美国-10
  network: ws
  port: 40707
  server: us10.jsyjiedian8.com
  tls: false
  type: vmess
  uuid: ee7c08a6-1682-4219-bbfc-14faca3843a1
  ws-opts:
    path: ''
proxy-groups:
- name: Auto
  proxies:
  - HK1
  - HK2
  - HK3
  - JP1
  - JP2
  - TW1
  - SG1
  - US1
  - 🇭🇰 香港_03
  - 🇭🇰+香港-07
  - 🇭🇰 香港_09
  - 🇯🇵+日本-13
  - 🇯🇵+日本-14
  - 🇯🇵+日本-15
  - 🇸🇬+新加坡-13
  - 🇸🇬+新加坡-14
  - 🇸🇬+新加坡-15
  - 🇺🇸 美国-08
  - 🇺🇸 美国-09
  - 🇺🇸 美国-10
  type: select
- interval: 300
  name: LoadBalance
  proxies:
  - HK1
  - HK2
  - HK3
  - JP1
  - JP2
  - TW1
  - SG1
  - US1
  - 🇭🇰 香港_03
  - 🇭🇰+香港-07
  - 🇭🇰 香港_09
  - 🇯🇵+日本-13
  - 🇯🇵+日本-14
  - 🇯🇵+日本-15
  - 🇸🇬+新加坡-13
  - 🇸🇬+新加坡-14
  - 🇸🇬+新加坡-15
  - 🇺🇸 美国-08
  - 🇺🇸 美国-09
  - 🇺🇸 美国-10
  strategy: consistent-hashing
  type: load-balance
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,google.com,Auto
- DOMAIN-SUFFIX,youtube.com,Auto
- DOMAIN-KEYWORD,google,Auto
- MATCH,DIRECT
