mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  nameserver:
  - 114.114.114.114
  - 8.8.8.8
proxies:
- name: 🇹🇼台湾 trojan
  type: trojan
  server: xj-tw2.zzsspnode.com
  port: 5418
  password: 87501829-4fcc-4954-9ecb-fd02d809dbcc
  skip-cert-verify: true
  sni: xj-tw2.zzsspnode.com
- name: 🇭🇰香港 trojan
  type: trojan
  server: tj.oopscat.com
  port: 7443
  password: '88888888'
  skip-cert-verify: true
  sni: tj.oopscat.com
proxy-groups:
- name: Auto
  type: select
  proxies:
  - 🇹🇼台湾 trojan
  - 🇭🇰香港 trojan
- name: LoadBalance
  type: load-balance
  strategy: consistent-hashing
  proxies:
  - 🇹🇼台湾 trojan
  - 🇭🇰香港 trojan
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- DOMAIN-SUFFIX,google.com,Auto
- DOMAIN-SUFFIX,youtube.com,Auto
- DOMAIN-KEYWORD,google,Auto
- MATCH,DIRECT
