allow-lan: true
dns:
  enable: true
  nameserver:
  - 114.114.114.114
  - 8.8.8.8
external-controller: 0.0.0.0:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
- name: 🇭🇰香港+06
  network: ws
  port: 80
  server: qsybgp1-1-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp1-1-1000ws.1000ws.top
    path: /grpcsg2/
- name: 🇭🇰香港+07
  network: ws
  port: 80
  server: qsybgp2-1-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp2-1-1000ws.1000ws.top
    path: /grpcsg2/
- name: 🇯🇵日本+03
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcjapan2/?ed=2560
- name: 🇯🇵日本+04
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcjapan2/?ed=2560
- name: 🇹🇼台湾+03
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpchongkong1/
- name: 🇸🇬新加坡+03
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcsg1/
- name: 🇺🇸美国+01
  network: ws
  port: 80
  server: qsybgp1-1-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp1-1-1000ws.1000ws.top
    path: /grpcus1/
- name: 🇺🇸美国+03
  network: ws
  port: 80
  server: qsybgp3-1000ws.1000ws.top
  tls: false
  type: vless
  udp: true
  uuid: a9f601ba-de1a-4718-b93d-134eb690901f
  ws-opts:
    headers:
      Host: qsybgp3-1000ws.1000ws.top
    path: /grpcus1/
proxy-groups:
- name: Auto
  proxies:
  - 🇭🇰香港+06
  - 🇭🇰香港+07
  - 🇯🇵日本+03
  - 🇯🇵日本+04
  - 🇹🇼台湾+03
  - 🇸🇬新加坡+03
  - 🇺🇸美国+01
  - 🇺🇸美国+03
  type: select
- interval: 300
  name: LoadBalance
  proxies:
  - 🇭🇰香港+06
  - 🇭🇰香港+07
  - 🇯🇵日本+03
  - 🇯🇵日本+04
  - 🇹🇼台湾+03
  - 🇸🇬新加坡+03
  - 🇺🇸美国+01
  - 🇺🇸美国+03
  strategy: consistent-hashing
  type: load-balance
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,google.com,Auto
- DOMAIN-SUFFIX,youtube.com,Auto
- DOMAIN-KEYWORD,google,Auto
- MATCH,DIRECT
